### PR TITLE
Deployment and Documentation

### PR DESCRIPTION
**Pull request by jlm123hi**
This should be the last pull request to be reviewed and merged. It contains the documentation and deployment scripts.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/downloader/6)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Hey, Joseph, I've added some initial comments. The high-level points are that I think we can consolidate the deploy scripts into a single script and reuse some existing scripts to make the work here easier.

---

Reviewed 1 of 9 files at r1.
Review status: 1 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[.travis.yml, line 5 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdsRI0XbG-hbI-VBeT:-KqdsRI0XbG-hbI-VBeU:btn27ec) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/.travis.yml#L5)):*
> ```YAML
> go:
>   - 1.8
> ```

If you use the directive `go_import_path` tests will run correctly from forks as well (which change the apparent go import path).

Like this: https://github.com/m-lab/alertmanager-github-receiver/blob/master/.travis.yml#L8

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdp9CFaaDrMmqMRgwa:-Kqdp9CFaaDrMmqMRgwb:b-93433x) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/.travis.yml#L28)):*
> ```YAML
>     - PROJECT_NAME_PRD=mlab-oti
>     - CLUSTER_NAME_PRD=downloader
>     - BUCKET_NAME_PRD=what-bucket-should-we-use-for-production
> ```

What constraints are on this name?

Would `downloader-mlab-oti` work? This matches the convention used by many other services: `<service name>-<project name>`

---

*[.travis.yml, line 34 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdprNy2QS5li2f0f_k:-KqdprNy2QS5li2f0f_l:b65p9k5) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/.travis.yml#L34)):*
> ```YAML
> 
> before_deploy:
>   - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
> ```

Is it possible to use https://github.com/m-lab/travis/blob/master/install_gcloud.sh instead?

If the installed versions are not up to date, then please update `install_gcloud.sh` to automatically run `components update`, since we should probably use the latest version for other projects too.

---

*[.travis.yml, line 46 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdsghl-ZZ-uMCXYEav:-Kqdsghl-ZZ-uMCXYEaw:bsg7wzp) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/.travis.yml#L46)):*
> ```YAML
> ## Sandbox
> - provider: script
>   script: $TRAVIS_BUILD_DIR/deployment/deploy-sandbox.sh
> ```

I suggest writing one `deploy.sh` script that accepts at least three parameters (maybe more are needed).

For example:
```
$TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-sandbox downloader maxmind-feed-sandbox
```

This should obviate the need for the global variables above and simplify the deploy scripts. Several of the scripts in https://github.com/m-lab/travis model how to accept parameters from the command line.

---

*[Dockerfile, line 20 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdu-5LOO60Z4JyrbD8:-Kqdu-5LOO60Z4JyrbD9:bp2mu5) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/Dockerfile#L20)):*
> ```Dockerfile
> CMD /go/bin/downloader -bucket=${DOWNLOADER_BUCKET}
> # Expose endpoint for prometheus metrics
> EXPOSE 8080
> ```

Please use 9090; this is the standard prometheus metrics port.

---

*[README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqe1Ud9AS2d6PD2XUcx:-Kqe1Ud9AS2d6PD2XUcy:b-37qhrd) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/README.md#L2)):*
> ```Markdown
> # downloader
> The Downloader tool runs on Google Container Engine and will scrape the Maxmind and Routeviews for new data. It will download them from the websites and place them in Google Cloud Storage in the specefied bucket. 
> ```

nit: please wrap lines at 80 columns.

In vim, the key combination `gqip` will do the right thing using the current text width setting.

---

*[deployment/deploy-production.sh, line 6 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqe-SLSTAIMhcaC8pdK:-Kqe-SLSTAIMhcaC8pdL:bjq3gr0) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/deployment/deploy-production.sh#L6)):*
> ```Shell
> set -x
> echo "Building Image"
> docker build -t gcr.io/${PROJECT_NAME_PRD}/${DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT .
> ```

I'd like to see the steps of "build and prepare docker image" separate from the steps of "deploy to k8s".

Is it possible to reuse https://github.com/m-lab/travis/blob/master/build_and_push_container.sh for the first part?

---

*[deployment/deploy-production.sh, line 17 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdyOHLWmdf-OhZyJap:-KqdyOHLWmdf-OhZyJaq:b-bjcvfd) ([raw file](https://github.com/m-lab/downloader/blob/14d7fb9e7d4f437a20ba05d0b8b02fad37f7a7a1/deployment/deploy-production.sh#L17)):*
> ```Shell
> gcloud --quiet config set container/cluster $CLUSTER_NAME_PRD
> echo "Setting Zone"
> gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
> ```

It's possible to determine the zone for a cluster at run time. This is a little more flexible in case we need to change zones in the future and it's one less variable / parameter to pass around.

For example: https://github.com/m-lab/prometheus-support/blob/master/kubectl.sh#L35

I've thought about moving this script to the travis repo, but haven't had a second user yet. What do you think of creating a second script to "deploy to k8s" that depends on `kubectl.sh`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/6#-:-Kqe7X665B1FCOKQtdBH:b-goo1df)*

**Comment by jlm123hi** [comment]
Review status: 1 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[.travis.yml, line 5 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdsRI0XbG-hbI-VBeT:-Kqy3u9-Z1EbeMm5OSQy:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If you use the directive `go_import_path` tests will run correctly from forks as well (which change the apparent go import path).

Like this: https://github.com/m-lab/alertmanager-github-receiver/blob/master/.travis.yml#L8
</blockquote></details>

Done.

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdp9CFaaDrMmqMRgwa:-Kqy5wh2i8Y2PvBVUJ3i:bco3c3m) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What constraints are on this name?

Would `downloader-mlab-oti` work? This matches the convention used by many other services: `<service name>-<project name>`
</blockquote></details>

Done. But somebody will need to set up the accounts needed for production,  because I (rightfully) don't have permissions.

---

*[.travis.yml, line 34 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdprNy2QS5li2f0f_k:-Kqy3vacFHqJYAK355Gk:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L34)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to use https://github.com/m-lab/travis/blob/master/install_gcloud.sh instead?

If the installed versions are not up to date, then please update `install_gcloud.sh` to automatically run `components update`, since we should probably use the latest version for other projects too.
</blockquote></details>

Done.

---

*[.travis.yml, line 46 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdsghl-ZZ-uMCXYEav:-Kr1BWmHqCUIP44KuC-_:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L46)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest writing one `deploy.sh` script that accepts at least three parameters (maybe more are needed).

For example:
```
$TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-sandbox downloader maxmind-feed-sandbox
```

This should obviate the need for the global variables above and simplify the deploy scripts. Several of the scripts in https://github.com/m-lab/travis model how to accept parameters from the command line.
</blockquote></details>

Done.

---

*[Dockerfile, line 20 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdu-5LOO60Z4JyrbD8:-Kr1GCMT1NozhGplbW6i:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/Dockerfile#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use 9090; this is the standard prometheus metrics port.
</blockquote></details>

Done.

---

*[README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqe1Ud9AS2d6PD2XUcx:-Kr1Fiied4ttS-AlVXS1:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please wrap lines at 80 columns.

In vim, the key combination `gqip` will do the right thing using the current text width setting.
</blockquote></details>

Done.

---

*[deployment/deploy-production.sh, line 6 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqe-SLSTAIMhcaC8pdK:-Kr1BLGnYFPcl9rpQNkV:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/deployment/deploy-production.sh#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'd like to see the steps of "build and prepare docker image" separate from the steps of "deploy to k8s".

Is it possible to reuse https://github.com/m-lab/travis/blob/master/build_and_push_container.sh for the first part?


</blockquote></details>

Done.

---

*[deployment/deploy-production.sh, line 17 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdyOHLWmdf-OhZyJap:-Kr1ClFHNyFbSBulSkUl:b-hzzx4v) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/deployment/deploy-production.sh#L17)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It's possible to determine the zone for a cluster at run time. This is a little more flexible in case we need to change zones in the future and it's one less variable / parameter to pass around.

For example: https://github.com/m-lab/prometheus-support/blob/master/kubectl.sh#L35

I've thought about moving this script to the travis repo, but haven't had a second user yet. What do you think of creating a second script to "deploy to k8s" that depends on `kubectl.sh`?
</blockquote></details>

Since I cannot edit the travis repo, you'll have to move it. Instead I am just using a copy for right now until one appears in the travis repo.

The actual deployment to k8s is one line, now that I am using your script. Do you still want me to break it out into a separate file? Or do you mean making the whole process of deploying to k8s, building image and all, available in the travis repository?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/6)*

**Comment by stephen-soltesz** [comment]
A few more comments -- smaller things. Looking good overall. The simplification in deploy.sh is great.

---

Reviewed 2 of 9 files at r2.
Review status: 3 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdp9CFaaDrMmqMRgwa:-Kr1YOjv_f6ZGjr1EQH9:bballa7) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L28)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

Done. But somebody will need to set up the accounts needed for production,  because I (rightfully) don't have permissions.
</blockquote></details>

Is there a plan for this? What is the plan? Are the steps documented or conversational? No wrong answers, just assessing.

---

*[.travis.yml, line 25 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1TZE1rDb-Tsvm3IoK:-Kr1TZE2bdbf4yhklJir:b-yvj708) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/.travis.yml#L25)):*
> ```YAML
> ## Sandbox
> - provider: script
>   script: $TRAVIS_BUILD_DIR/deployment/deploy.sh mlab-sandbox downloader maxmind-feed-sandbox $GCLOUD_SERVICE_KEY_BOX
> ```

Why does mlab-sandbox have a different bucket name format than mlab-staging and mlab-oti? Can it use the same?

---

*[kubectl.sh, line 1 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1YqZPdQkCWYmeBfCb:-Kr1YqZPdQkCWYmeBfCc:bxe89kl) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/kubectl.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Please remove in favor of m-lab/travis/kudo.sh

---

*[README.md, line 27 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1rPGlVnjKVMu09TNO:-Kr1rPGmWMI_-p36RHmM:bnd6mxk) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/README.md#L27)):*
> ```Markdown
> 
> ### Deployment Configuration
> The deployment scripts also expect a number of other environment variables to be
> ```

What needs to be updated here?

---

*[deployment/deploy.sh, line 12 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1_8aCa2cGYLKcLuEr:-Kr1_8aCa2cGYLKcLuEs:b-882qlf) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/deployment/deploy.sh#L12)):*
> ```Shell
> 
> echo $GCLOUD_SERVICE_KEY | base64 --decode -i > /tmp/${PROJECT_NAME}.json
> gcloud auth activate-service-account --key-file /tmp/${PROJECT_NAME}.json
> ```

Does this work as-is, without adding `source "${HOME}/google-cloud-sdk/path.bash.inc"`? I'm wondering if the system or user bash profile is updated by the install now? Not using  had caused problems for me in the past. Good to know if it's more convenient now.

---

*[deployment/deploy.sh, line 14 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1Zm5O1_Ct39T2JxdV:-Kr1Zm5O1_Ct39T2JxdW:b-rmkq5m) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/deployment/deploy.sh#L14)):*
> ```Shell
> gcloud auth activate-service-account --key-file /tmp/${PROJECT_NAME}.json
> 
> ./travis/build_and_push_container.sh gcr.io/${PROJECT_NAME}/downloader:$TRAVIS_COMMIT $PROJECT_NAME
> ```

Please respect 80-column text width and continue lines with "\\" where needed.

---

*[deployment/deploy-production.sh, line 17 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-KqdyOHLWmdf-OhZyJap:-Kr1_TvUgZP3yAj--DtJ:brvtauh) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/deployment/deploy-production.sh#L17)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

Since I cannot edit the travis repo, you'll have to move it. Instead I am just using a copy for right now until one appears in the travis repo.

The actual deployment to k8s is one line, now that I am using your script. Do you still want me to break it out into a separate file? Or do you mean making the whole process of deploying to k8s, building image and all, available in the travis repository?
</blockquote></details>

You're right. The deploy script is simple enough now that it lgtm. Thank you for taking the time to update and simplify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/6#-:-Kr1s-vMPpUxc4y_ueqZ:b-h8bwfl)*

**Comment by jlm123hi** [comment]
Review status: 3 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdp9CFaaDrMmqMRgwa:-Kr238-mvTUOCtStg6vQ:b-w86rko) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there a plan for this? What is the plan? Are the steps documented or conversational? No wrong answers, just assessing.
</blockquote></details>

I don't really have a specific plan for this. It should be ~30 minutes worth of work, max. Everything one needs to know to actually do it should be in the README.md for this repo. But I figured it would probably be easier to just walk someone through it.

---

*[.travis.yml, line 25 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1TZE1rDb-Tsvm3IoK:-Kr22dqOEZpswLA6x5dr:bp7ysmd) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/.travis.yml#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why does mlab-sandbox have a different bucket name format than mlab-staging and mlab-oti? Can it use the same?
</blockquote></details>

I had originally done it because the bucket already existed with some old data in it, and so I figured it was better to use that. Though, I accidentally deleted and recreated the sandbox bucket during development, so it's a moot point now. I changed it over to a new one with a matching naming scheme.

---

*[README.md, line 27 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1rPGlVnjKVMu09TNO:-Kr21i89UNGWIxwUR08M:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/README.md#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What needs to be updated here?
</blockquote></details>

Done.

---

*[deployment/deploy.sh, line 12 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1_8aCa2cGYLKcLuEr:-Kr21kTEsUt5ZvYehwpO:b-zemiq9) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/deployment/deploy.sh#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this work as-is, without adding `source "${HOME}/google-cloud-sdk/path.bash.inc"`? I'm wondering if the system or user bash profile is updated by the install now? Not using  had caused problems for me in the past. Good to know if it's more convenient now.
</blockquote></details>

Surprisingly, it does. I think it's something about running the install gcloud script in the travis before deploy section that makes it work.

---

*[deployment/deploy.sh, line 14 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1Zm5O1_Ct39T2JxdV:-Kr21v1mhkENpRTVq9WC:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/deployment/deploy.sh#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please respect 80-column text width and continue lines with "\\" where needed.
</blockquote></details>

Done.

---

*[kubectl.sh, line 1 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1YqZPdQkCWYmeBfCb:-Kr21w48U3t4zuVxEWI4:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/kubectl.sh#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please remove in favor of m-lab/travis/kudo.sh
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/6)*

**Comment by stephen-soltesz** [comment]
This should be the last round. With the suggested cleanups :lgtm:

---

Reviewed 1 of 9 files at r2, 2 of 5 files at r3.
Review status: 4 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdp9CFaaDrMmqMRgwa:-Kr26ouTud2x_1ZNAdnm:b3wmksq) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L28)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

I don't really have a specific plan for this. It should be ~30 minutes worth of work, max. Everything one needs to know to actually do it should be in the README.md for this repo. But I figured it would probably be easier to just walk someone through it.
</blockquote></details>

That sounds like a good plan. I suggest picking a person and scheduling it -- probably after the code reviews are complete. I'm happy to help.

---

*[.travis.yml, line 25 at r2](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr1TZE1rDb-Tsvm3IoK:-Kr276YakZof0nYdY8D9:bb6mt9b) ([raw file](https://github.com/m-lab/downloader/blob/142ac92d44e9305bcadb2614a1d24722d1ba026d/.travis.yml#L25)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

I had originally done it because the bucket already existed with some old data in it, and so I figured it was better to use that. Though, I accidentally deleted and recreated the sandbox bucket during development, so it's a moot point now. I changed it over to a new one with a matching naming scheme.
</blockquote></details>

:+1:

---

*[README.md, line 32 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr2E5_6EyoeqvR0A0NF:-Kr2E5_6EyoeqvR0A0NG:brzu9zd) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/README.md#L32)):*
> ```Markdown
> parameters passed into the deploy.sh command, along with the service account
> JSON key, encoded in base64 form. The deploy.sh command takes the form:
> `deploy.sh <project name> <cluster name> <bucket name> <base64 service account
> ```

Style suggestion: for longer commands, I suggest using a longer block to create a visual break that works in raw ascii and formatted markdown. This way you can use the same conventions as you would in a shell script or line continuation.

For example:

```
    ```
    deploy.sh <project name> <cluster name> <bucket name> \
        <base64 service account key text>
    ```
```

---

*[README.md, line 40 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr2Ei3ZC_4MMTHo7auW:-Kr2Ei3ZC_4MMTHo7auX:bmqazo1) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/README.md#L40)):*
> ```Markdown
> deployment, if you wish. But you need to store the key file in a kubernetes
> secret, named downloader-app-key, so that the deployment config can find and
> mount it for use by the app. You can set it with: `kubectl create secret generic
> ```

Similarly here.

---

*[deployment/deploy.sh, line 15 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr27Tc_A2l-xzVQmdl0:-Kr27TcaTwgNgycC8ito:b5ez8h7) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/deploy.sh#L15)):*
> ```Shell
> 
> ./travis/build_and_push_container.sh \
> gcr.io/${PROJECT_NAME}/downloader:$TRAVIS_COMMIT $PROJECT_NAME
> ```

Ah, and by convention, please indent line continuations four spaces.

i.e.

```
./travis/build_and_push_container.sh \
    gcr.io/${PROJECT_NAME}/downloader:$TRAVIS_COMMIT $PROJECT_NAME
```

---

*[deployment/templates/deploy-downloader.yaml, line 7 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr289TiHeVfjNicwXi8:-Kr289TiHeVfjNicwXi9:b-8mt8m8) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/templates/deploy-downloader.yaml#L7)):*
> ```YAML
>   metadata:
>     annotations:
>       prometheus.io/scrape: 'true'
> ```

This annotation on the deployment should not be needed.

The annotation on the pod template below is necessary.

---

*[deployment/templates/deploy-downloader.yaml, line 48 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr27zkds1wlFt1h9ZUV:-Kr27zkds1wlFt1h9ZUW:b-8gdis4) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/templates/deploy-downloader.yaml#L48)):*
> ```YAML
>           name: downloader
>           ports:
>           - containerPort: 8080
> ```

9090?

---

*[deployment/templates/deploy-downloader.yaml, line 58 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr2F9swBs87qEbcJkli:-Kr2F9swBs87qEbcJklj:bqo1ymt) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/templates/deploy-downloader.yaml#L58)):*
> ```YAML
>         securityContext: {}
>         terminationGracePeriodSeconds: 30
> kind: List
> ```

Since there is only one deployment, I suggest eliminating the List.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/6#-:-Kr2FIeFiHXMOSSk_R6F:b-joui1j)*

**Comment by jlm123hi** [comment]
Review status: 3 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kqdp9CFaaDrMmqMRgwa:-Kr2QKRwJJY3FTwUtUFL:b-c89mpz) ([raw file](https://github.com/m-lab/downloader/blob/3a7b316cb66aa7ed3aee436f6a3969cb58652ac6/.travis.yml#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

That sounds like a good plan. I suggest picking a person and scheduling it -- probably after the code reviews are complete. I'm happy to help.
</blockquote></details>

Well then, I guess I'll schedule it with you as soon as I get this last PR merged.

---

*[README.md, line 32 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr2E5_6EyoeqvR0A0NF:-Kr2N2Cc-Jrb7EsDge6m:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/README.md#L32)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Style suggestion: for longer commands, I suggest using a longer block to create a visual break that works in raw ascii and formatted markdown. This way you can use the same conventions as you would in a shell script or line continuation.

For example:

```
    ```
    deploy.sh <project name> <cluster name> <bucket name> \
        <base64 service account key text>
    ```
```
</blockquote></details>

Done.

---

*[README.md, line 40 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr2Ei3ZC_4MMTHo7auW:-Kr2N5EJW0SSvxhGKotY:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/README.md#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Similarly here.
</blockquote></details>

Done.

---

*[deployment/deploy.sh, line 15 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr27Tc_A2l-xzVQmdl0:-Kr2MNyFbt6xNuyhL-T9:b26yv5j) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/deploy.sh#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, and by convention, please indent line continuations four spaces.

i.e.

```
./travis/build_and_push_container.sh \
    gcr.io/${PROJECT_NAME}/downloader:$TRAVIS_COMMIT $PROJECT_NAME
```

</blockquote></details>

I KNEW something about that looked wrong, I just couldn't place my finger on it.

---

*[deployment/templates/deploy-downloader.yaml, line 7 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr289TiHeVfjNicwXi8:-Kr2M3FuECfiN1-_ye-b:b-74bepi) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/templates/deploy-downloader.yaml#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This annotation on the deployment should not be needed.

The annotation on the pod template below is necessary.
</blockquote></details>

Done. Removed it.

---

*[deployment/templates/deploy-downloader.yaml, line 48 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr27zkds1wlFt1h9ZUV:-Kr2M5JzcWbbN_IaA5zA:bqlcb5d) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/templates/deploy-downloader.yaml#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

9090?
</blockquote></details>

Done. I feel really silly for missing this one.

---

*[deployment/templates/deploy-downloader.yaml, line 58 at r3](https://reviewable.io:443/reviews/m-lab/downloader/6#-Kr2F9swBs87qEbcJkli:-Kr2M8_5B2QCaSzmJiKC:b-398ora) ([raw file](https://github.com/m-lab/downloader/blob/66b6202ea55e905a9498f4a99165a7d17f7e7a23/deployment/templates/deploy-downloader.yaml#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since there is only one deployment, I suggest eliminating the List.
</blockquote></details>

I added that when I was trying to understand how kubernetes yaml files worked. Removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/6)*

**Pull request merged**
