### PR TITLE
Merge pull request #15 from m-lab/integration

### PR DESCRIPTION
**Pull request by pboothe**
push integration to master to deploy to prod

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/downloader/22)

### CODE REVIEW

**Comment by pboothe** [comment]
Deploys the staging version to production.  All alerts have cleared.  If this PR is approved, I will merge it around 5pm eastern time today (Thursday).

**Comment by pboothe** [comment]
Ugh. I accidentally merged already. I am very sorry.

**Comment by stephen-soltesz** [comment]
lgtm? Is this PR still needed? I'm confused.

**Comment by pboothe** [comment]
This PR is no longer required.

**Pull request closed without merging**
