### PR TITLE
The code to download maxmind.

### PR DESCRIPTION
**Pull request by jlm123hi**
This should only be pulled AFTER api-sandbox.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/downloader/3)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader.go, line 48 at r1](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTLfpXcN253JcYmnvU:-KqTLfpXcN253JcYmnvV:b-l8w463) ([raw file](https://github.com/m-lab/downloader/blob/2a34117e15bfac305f5b07e7be2b48bda364e36c/downloader.go#L48)):*
> ```Go
> 	//    LastSuccessTime.Inc()
> 	LastSuccessTime = prometheus.NewGauge(prometheus.GaugeOpts{
> 		Name: "downloader_Last_Successful_Time",
> ```

Prefixing the metric name with the application is great and consistent with the recommended best practices - https://prometheus.io/docs/practices/naming/

Please update all metrics to use consistent "snake case", e.g. in this case downloader_last_successful_time. Please do not use capital letters in metric names or labels.

---

*[downloader.go, line 48 at r1](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTNnADNs13vYtYnwPY:-KqTNnADNs13vYtYnwPZ:b-67knhd) ([raw file](https://github.com/m-lab/downloader/blob/2a34117e15bfac305f5b07e7be2b48bda364e36c/downloader.go#L48)):*
> ```Go
> 	//    LastSuccessTime.Inc()
> 	LastSuccessTime = prometheus.NewGauge(prometheus.GaugeOpts{
> 		Name: "downloader_Last_Successful_Time",
> ```

Rather than "downloader_last_successful_time", I suggest "downloader_last_success_time_seconds". This follows the general pattern of `<application>_<name>_<unit>`. The variable name "LastSuccessTime" is the camel case inverse of "last_success_time" and "seconds" is the unit on a unix time stamp.

This convention helps prometheus users easily interpret new metrics without necessarily needing to review the original source code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by jlm123hi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader.go, line 48 at r1](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTLfpXcN253JcYmnvU:-KqTt34Gl6kNQoI9D05q:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/2a34117e15bfac305f5b07e7be2b48bda364e36c/downloader.go#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Prefixing the metric name with the application is great and consistent with the recommended best practices - https://prometheus.io/docs/practices/naming/

Please update all metrics to use consistent "snake case", e.g. in this case downloader_last_successful_time. Please do not use capital letters in metric names or labels.
</blockquote></details>

Done.

---

*[downloader.go, line 48 at r1](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTNnADNs13vYtYnwPY:-KqTt3SWIE9B0R2xFFOi:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/2a34117e15bfac305f5b07e7be2b48bda364e36c/downloader.go#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Rather than "downloader_last_successful_time", I suggest "downloader_last_success_time_seconds". This follows the general pattern of `<application>_<name>_<unit>`. The variable name "LastSuccessTime" is the camel case inverse of "last_success_time" and "seconds" is the unit on a unix time stamp.

This convention helps prometheus users easily interpret new metrics without necessarily needing to review the original source code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by stephen-soltesz** [comment]
Thanks, :+1: the metrics look good!

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader.go, line 58 at r2](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTyC0fV1w0pA3H2Ek6:-KqTyC0g-QRh7jiDx-tt:b-ym7a7e) ([raw file](https://github.com/m-lab/downloader/blob/06ebae28e643d2b30e21592a6059397be267d10f/downloader.go#L58)):*
> ```Go
> 	//    FailedDownloadCount.Inc()
> 	FailedDownloadCount = prometheus.NewCounterVec(prometheus.CounterOpts{
> 		Name: "downloader_download_failed",
> ```

If this metric is also a count, I suggest adding the suffix `_count` here like the others below. Possibly "downloader_failure_count"

---

*[downloader.go, line 60 at r2](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTyYJKpViuN9dEd1pF:-KqTyYJKpViuN9dEd1pG:b-w9cjze) ([raw file](https://github.com/m-lab/downloader/blob/06ebae28e643d2b30e21592a6059397be267d10f/downloader.go#L60)):*
> ```Go
> 		Name: "downloader_download_failed",
> 		Help: "Increments every time a download maxes out our number of retries.",
> 	}, []string{"DownloadType"})
> ```

As discussed by IM, lower case for metric and label names is preferred. The label values can take any form as long as there are not too many of them, ~10 to ~100, with preference toward fewer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3#-:-KqTykV_2hO6EbSwVzel:b2xu9f7)*

**Comment by jlm123hi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader.go, line 58 at r2](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTyC0fV1w0pA3H2Ek6:-KqU0lX6ZoK-P0TAW1Qe:bylcqvs) ([raw file](https://github.com/m-lab/downloader/blob/06ebae28e643d2b30e21592a6059397be267d10f/downloader.go#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If this metric is also a count, I suggest adding the suffix `_count` here like the others below. Possibly "downloader_failure_count"
</blockquote></details>

Good catch. Fixed up.

---

*[downloader.go, line 60 at r2](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqTyYJKpViuN9dEd1pF:-KqU0wx_IiF85WgXd6GA:bryyru3) ([raw file](https://github.com/m-lab/downloader/blob/06ebae28e643d2b30e21592a6059397be267d10f/downloader.go#L60)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

As discussed by IM, lower case for metric and label names is preferred. The label values can take any form as long as there are not too many of them, ~10 to ~100, with preference toward fewer.
</blockquote></details>

Sorry, I don't know how I missed this one. Situation remedied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[downloader.go, line 106 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUID0wVEHWI7Bn21kv:-KqUID0wVEHWI7Bn21kw:b-h7dzmm) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L106)):*
> ```Go
> 	}
> 	// Get a handle on our object in GCS where we will store the file
> 	filename := dc.url[strings.LastIndex(dc.url, "/")+1-dc.backChars:]
> ```

move this block of  code just above where you do the io.Copy.  Then consider wrapping the whole block (this plus the io.Copy block, and w.Close) into a separate function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[downloader.go, line 99 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUMQo4cQ1UH3oXx1hq:-KqUMQo4cQ1UH3oXx1hr:b7qg9yd) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L99)):*
> ```Go
> }
> 
> // download takes a fully populated downloadConfig and downloads the file specefied by the URL, storing it in the store implementation that is passed in, in the directory specefied by the prefix, given the number of extra characters from the URL specified by backChars.
> ```

I think it would be much cleaner for the config to provide the url prefix, and filename, and construct the url from them, rather than trying to extract the filename from the url.  Alternatively, use url library functions to get the filename, rather than dc.backChars.

---

*[downloader.go, line 170 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUMuZKYCRkZWamGJ3y:-KqUMuZKYCRkZWamGJ3z:b-m75v8q) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L170)):*
> ```Go
> // getHashOfGCSFile takes an implementation of the fileObject interface and returns the MD5 hash of that fileObject, or an error if we cannot get the hash
> func getHashOfFile(obj fileObject) ([]byte, error) {
> 	attrs, err := obj.getAttrs()
> ```

Better to just have getMD5 function directly on the fileObject, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by jlm123hi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[downloader.go, line 99 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUMQo4cQ1UH3oXx1hq:-KqUTXDzccwoGMAOWIkb:b-1hmvcg) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L99)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think it would be much cleaner for the config to provide the url prefix, and filename, and construct the url from them, rather than trying to extract the filename from the url.  Alternatively, use url library functions to get the filename, rather than dc.backChars.
</blockquote></details>

Constructing the URL from the filename and prefix is not possible as the routeviews URLs will not be known until runtime, and we just get them as URLs, rather than filenames and prefixes. 

As for the URL library functions, there are none that do what we want.  They all handle more difficult things like protocols, usernames, and queries, rather than simple string manipulations. 

I wholeheartedly agree that backChars is an ugly hack. But I can't think of any way to do it that is much cleaner, while still giving us the ability to sample different parts of the URL for the filenames we need.

---

*[downloader.go, line 106 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUID0wVEHWI7Bn21kv:-KqUVPo-XeSKuMcaxy2c:b-4knsh0) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L106)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

move this block of  code just above where you do the io.Copy.  Then consider wrapping the whole block (this plus the io.Copy block, and w.Close) into a separate function.
</blockquote></details>

I agree that moving the code is a good idea, and I did it.

But if we break it out into a separate function, then we still need to have an error catch here so that the error can propagate. Plus, filename and obj are used later in the code as well, so they cannot be moved. So in the end it would be no easier to understand and even more messy. I think that there is a much stronger case for moving the actual web requests and validation into a separate function, if you're keen on breaking down this messy method.

---

*[downloader.go, line 170 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUMuZKYCRkZWamGJ3y:-KqUWLk-hSZbW5mnmJCi:b3i339t) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L170)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Better to just have getMD5 function directly on the fileObject, I think.
</blockquote></details>

I completely agree and will do that immediately. In fact, I'll just merge the whole fileAttributes and fileObject interfaces together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[downloader.go, line 58 at r4](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcaWN62kyfP23ZkhfH:-KqcaWN62kyfP23ZkhfI:bwffwb) ([raw file](https://github.com/m-lab/downloader/blob/c60870144bf5bbba48b710b45274d6ccacd8ab09/downloader.go#L58)):*
> ```Go
> 
> // download takes a fully populated downloadConfig and downloads the file specefied by the URL, storing it in the store implementation that is passed in, in the directory specefied by the prefix, given the number of extra characters from the URL specified by backChars.
> func download(config interface{}) (error, bool) {
> ```

Add documentation about the return value, what is the difference between

error is not nil, true
error is not nil, false
error is nil, true
error is nil, false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by jlm123hi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[downloader.go, line 99 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUMQo4cQ1UH3oXx1hq:-KqceTBxeZ2WgPmLT_7U:b6qfy2k) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L99)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

Constructing the URL from the filename and prefix is not possible as the routeviews URLs will not be known until runtime, and we just get them as URLs, rather than filenames and prefixes. 

As for the URL library functions, there are none that do what we want.  They all handle more difficult things like protocols, usernames, and queries, rather than simple string manipulations. 

I wholeheartedly agree that backChars is an ugly hack. But I can't think of any way to do it that is much cleaner, while still giving us the ability to sample different parts of the URL for the filenames we need.
</blockquote></details>

Added a todo, as per our in-person discussion.

---

*[downloader.go, line 106 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUID0wVEHWI7Bn21kv:-KqceLcX-3aucwp3enD1:bo1kgyy) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L106)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

I agree that moving the code is a good idea, and I did it.

But if we break it out into a separate function, then we still need to have an error catch here so that the error can propagate. Plus, filename and obj are used later in the code as well, so they cannot be moved. So in the end it would be no easier to understand and even more messy. I think that there is a much stronger case for moving the actual web requests and validation into a separate function, if you're keen on breaking down this messy method.
</blockquote></details>

Discussed in person, conclusion was to not break it out into a separate function.

---

*[downloader.go, line 170 at r3](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqUMuZKYCRkZWamGJ3y:-KqceGDHhgqAr43ZMT-d:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/2ebe37f56dd253b3fb552c1e9db809a57cc4243d/downloader.go#L170)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

I completely agree and will do that immediately. In fact, I'll just merge the whole fileAttributes and fileObject interfaces together.
</blockquote></details>

Done.

---

*[downloader.go, line 58 at r4](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcaWN62kyfP23ZkhfH:-KqceRB01sEDgYACOM3b:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/c60870144bf5bbba48b710b45274d6ccacd8ab09/downloader.go#L58)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add documentation about the return value, what is the difference between

error is not nil, true
error is not nil, false
error is nil, true
error is nil, false
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[downloader.go, line 128 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcqdijW-yjeJM12BAs:-KqcqdijW-yjeJM12BAt:bf6n8en) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader.go#L128)):*
> ```Go
> }
> 
> // checkIfHashIsUniqueInList takes an MD5 hash, a slice of fileAttributes, and a filename corresponding to the MD5 hash. It will return false if it finds another file in the slice with a matching MD5 and a different filename. Otherwise, it will return true.
> ```

split the documentation into  multiple lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[downloader_test.go, line 1 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcrYfDY1Gh4nytJKfk:-KqcrYfDY1Gh4nytJKfl:b-90qbf0) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader_test.go#L1)):*
> ```Go
> package main
> ```

change package name to download_test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[downloader.go, line 103 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcscDgQXWm-qSRwBqD:-KqcscDgQXWm-qSRwBqE:b-z8hmwf) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader.go#L103)):*
> ```Go
> }
> 
> // runFunctionWithRetry takes a struct and a function to pass it to and will run that function, giving it that argument. If the function returns a non-nil error, the function will be retried unless it also returned a boolean flag specefying that it encountered an unrecoverable error. It also takes a retryTimeMin to wait after the first failure before retrying. After each failure, it will wait twice as long until it reaches the retryTimeMax, which makes it return the last error it encountered.
> ```

split docs into multiple lines, and for all the following cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[downloader_test.go, line 111 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcwEq5UaWpLkJDWO8L:-KqcwEq5UaWpLkJDWO8M:bqm1en0) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader_test.go#L111)):*
> ```Go
> }
> 
> func Test_download(t *testing.T) {
> ```

func TestXxx(*testing.T)

Check testing func naming convention for golang. 
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader_test.go, line 177 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-Kqcy0Eaavg2BmBPWmUP:-Kqcy0Eaavg2BmBPWmUQ:b6nefj4) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader_test.go#L177)):*
> ```Go
> 	}
> 	if err, force := download(nil); err == nil || force != true {
> 		t.Errorf("FUNCTION DID NOT REJECT INVALID INTERFACE!!!")
> ```

Keep the error message consistent, no need all capital here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[downloader_test.go, line 203 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqdesDJreQSKEdnVLFv:-KqdesDJreQSKEdnVLFw:b-ppxuro) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader_test.go#L203)):*
> ```Go
> }
> 
> func Test_runFunctionWithRetry(t *testing.T) {
> ```

change func name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[downloader_test.go, line 258 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-Kqdeyo7uzXVWVpwlAAK:-Kqdeyo7uzXVWVpwlAAL:bl0v130) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader_test.go#L258)):*
> ```Go
> }
> 
> func Test_determineIfFileIsNew(t *testing.T) {
> ```

change func name, and all following cases

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 14 unresolved discussions.

---

*[downloader_test.go, line 204 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-Kqdg3IBfl45dk-cqKj4:-Kqdg3IBfl45dk-cqKj5:bap4uq7) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader_test.go#L204)):*
> ```Go
> 
> func Test_runFunctionWithRetry(t *testing.T) {
> 	tests := []struct {
> ```

Add some explanation about the test design,  set force as true/false,  why set retryTimeMax as  0, 50, 5000, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by jlm123hi** [comment]
Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[downloader.go, line 103 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcscDgQXWm-qSRwBqD:-KqdhgjwKXjyAr6Y9_2d:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader.go#L103)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

split docs into multiple lines, and for all the following cases.
</blockquote></details>

Done.

---

*[downloader.go, line 128 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcqdijW-yjeJM12BAs:-KqdhgH6_pgHO0dn_YSj:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/downloader.go#L128)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

split the documentation into  multiple lines
</blockquote></details>

Done.

---

*[download/common_test.go, line 1 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcrYfDY1Gh4nytJKfk:-Kqdhhk_K0wT4Zf3xLIX:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/download/common_test.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

change package name to download_test
</blockquote></details>

Done.

---

*[download/common_test.go, line 111 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqcwEq5UaWpLkJDWO8L:-KqdhiHWfYK99yC5Pa4n:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/download/common_test.go#L111)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

func TestXxx(*testing.T)

Check testing func naming convention for golang. 
 
</blockquote></details>

Done.

---

*[download/common_test.go, line 177 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-Kqcy0Eaavg2BmBPWmUP:-KqdhinSLybV9ORzYgRp:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/download/common_test.go#L177)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Keep the error message consistent, no need all capital here.
</blockquote></details>

Done.

---

*[download/common_test.go, line 203 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqdesDJreQSKEdnVLFv:-KqdhrACJ9YW0n92BvQP:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/download/common_test.go#L203)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

change func name
</blockquote></details>

Done.

---

*[download/common_test.go, line 204 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-Kqdg3IBfl45dk-cqKj4:-KqdjlGhkocIk8kU3L_2:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/download/common_test.go#L204)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add some explanation about the test design,  set force as true/false,  why set retryTimeMax as  0, 50, 5000, etc.
</blockquote></details>

Done.

---

*[download/common_test.go, line 258 at r5](https://reviewable.io:443/reviews/m-lab/downloader/3#-Kqdeyo7uzXVWVpwlAAK:-KqdhptZYi_6JNiFqBAO:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/3e8317ee7b7fedfafc78ab1f1b3c0454543a6e99/download/common_test.go#L258)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

change func name, and all following cases
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[download/maxmind.go, line 10 at r6](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqhhqXyWsMNILdiGjZD:-KqhhqXyWsMNILdiGjZE:bfkw94c) ([raw file](https://github.com/m-lab/downloader/blob/995385d930c506921316eea990865f3b5b999dbd/download/maxmind.go#L10)):*
> ```Go
> 
> // The list of URLs to download from Maxmind
> var MaxmindURLs []string = []string{
> ```

make them const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by jlm123hi** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[download/maxmind.go, line 10 at r6](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqhhqXyWsMNILdiGjZD:-KqiPGN5GEcvylPaVkGk:b9ov7ic) ([raw file](https://github.com/m-lab/downloader/blob/995385d930c506921316eea990865f3b5b999dbd/download/maxmind.go#L10)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

make them const
</blockquote></details>

Neither slices nor arrays in Go can be made constants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[download/maxmind.go, line 10 at r6](https://reviewable.io:443/reviews/m-lab/downloader/3#-KqhhqXyWsMNILdiGjZD:-KqiS1220mT7rl-TMJK1:b32w0x) ([raw file](https://github.com/m-lab/downloader/blob/995385d930c506921316eea990865f3b5b999dbd/download/maxmind.go#L10)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

Neither slices nor arrays in Go can be made constants.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/3#-:-KqiS5vLq3blqWYiZItJ:bnfp4nl)*

**Pull request merged**
