### PR TITLE
Added the untestable code.

### PR DESCRIPTION
**Pull request by jlm123hi**
This should only be reviewed/merged after the routeviews PR.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/downloader/5)

### CODE REVIEW

**Comment by pboothe** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[downloader.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-KqdrmAXrAMoFDpSRF1k:-KqdrmAXrAMoFDpSRF1l:bion38l) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L66)):*
> ```Go
> 	}()
> 	bucketName := flag.String("bucket", "", "Specify the bucket name to store the results in.")
> 	flag.Parse()
> ```

parse flags before anything else please.

---

*[downloader.go, line 90 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-KqdpDONZemWgqBkcZPD:-KqdpDONZemWgqBkcZPE:b8nn7bk) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L90)):*
> ```Go
> 		}
> 
> 		routeviewIPv4Err := downloadRouteviewsFiles("http://data.caida.org/datasets/routing/routeviews-prefix2as/pfx2as-creation.log", "RouteViewIPv4/", &lastDownloadedV4, fileStore)
> ```

This function should be `downloadCaidaRouteviewsFiles`. Properly understood, "routeviews files" can only come from http://archive.routeviews.org 

---

*[downloader.go, line 103 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-Kqdp1NQ5ERzbSV2SmKR:-Kqdp1NQ5ERzbSV2SmKS:b-xm6d83) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L103)):*
> ```Go
> 			metrics.LastSuccessTime.SetToCurrentTime()
> 		}
> 		time.Sleep(time.Duration(genUniformSleepTime(averageHoursBetweenUpdateChecks, windowForRandomTimeBetweenUpdateChecks)) * time.Hour)
> ```

`genUniformSleepTime()` does not actually generate a time? That makes me sad.

---

*[downloader.go, line 192 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-KqdquiIPS4OgZKTlNvP:-KqdquiIPS4OgZKTlNvQ:b-obzx58) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L192)):*
> ```Go
> 
> 	// Check to make sure we didn't just download a duplicate, and delete it if we did.
> 	fileNew := determineIfFileIsNew(dc.store, dc.prefix+filename, dc.prefix[:dc.dedupePrefixDepth]+filename[:dc.backChars])
> ```

call this `isFileNew` and rewrite the if statement to be:
```go
if ! isFileNew(...) {
```

Fewer variables is always better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/5)*

**Comment by jlm123hi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[downloader.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-KqdrmAXrAMoFDpSRF1k:-KqiR6Z0kE5betGhwWuD:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L66)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

parse flags before anything else please.
</blockquote></details>

Done.

---

*[downloader.go, line 90 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-KqdpDONZemWgqBkcZPD:-KqiM7RTHu7z_wbI6he-:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L90)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This function should be `downloadCaidaRouteviewsFiles`. Properly understood, "routeviews files" can only come from http://archive.routeviews.org 
</blockquote></details>

Done.

---

*[downloader.go, line 103 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-Kqdp1NQ5ERzbSV2SmKR:-KqiM6ctveDPh8IBWAPL:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L103)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`genUniformSleepTime()` does not actually generate a time? That makes me sad.
</blockquote></details>

Done.

---

*[downloader.go, line 192 at r1](https://reviewable.io:443/reviews/m-lab/downloader/5#-KqdquiIPS4OgZKTlNvP:-KqiM5sWQVcGTsqaJXDz:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/08c4a5064c4e94c4b370f20c3da7fb797085676c/downloader.go#L192)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

call this `isFileNew` and rewrite the if statement to be:
```go
if ! isFileNew(...) {
```

Fewer variables is always better.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/5)*

**Comment by pboothe** [comment]
Looks like download.go is missing from this pr?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/5#-:-KqjB64NKoc32c70aN82:bj7ja8b)*

**Comment by jlm123hi** [comment]
I see downloader.go just fine?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/5#-:-KqwuEKJmb4VWAZgT8s5:b-pwchtz)*

**Comment by pboothe** [comment]
Sorry, I was referring to the idea that some code was missing from this PR, before we had our conversation on Friday where you explained what was up.

One optional comment.

:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[downloader.go, line 63 at r2](https://reviewable.io:443/reviews/m-lab/downloader/5#-Kr2HDQzpELGKvqRgRR8:-Kr2HDQzpELGKvqRgRR9:bkodod2) ([raw file](https://github.com/m-lab/downloader/blob/e9c74c687e975d99c7cbf940af45219e26647497/downloader.go#L63)):*
> ```Go
> 		}
> 
> 		routeviewIPv4Err := download.DownloadCaidaRouteviewsFiles("http://data.caida.org/datasets/routing/routeviews-prefix2as/pfx2as-creation.log", "RouteViewIPv4/", &lastDownloadedV4, fileStore)
> ```

This line is long. With this line and its sibling, if I were writing this I would break them up as follows:
```go
routeviewIPv4Err := download.DownloadCaidaRouteviewsFiles(
    "http://data.caida.org/datasets/routing/routeviews-prefix2as/pfx2as-creation.log", 
    "RouteViewIPv4/", 
    &lastDownloadedV4, 
    fileStore)
```

This comment is optional, but would make things look better IMO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/5#-:-Kqxr5sfiKaMj26R9iVC:bf6kogi)*

**Pull request merged**
