### PR TITLE
Download databases only every 24h, not ever 8h

### PR DESCRIPTION
**Pull request by nkinkade**
The downloader runs in 3 projects and downloads 6 files (GeoLite Country, City means that each project may be downloading the database around 18 times per day. Across 3 projects that is 54 downloads per day. The MaxMind download limit for GeoLite accounts is only 30. This commit changes the average download interval to 24h. The databases we use are only updated twice a week (Tue and Fri):

https://support.maxmind.com/hc/en-us/articles/4408216129947-Download-and-Update-Databases

I do no know how this was working before my [recent changes](https://github.com/m-lab/downloader/pull/54). I suspect that download limit accounting may not have been in effect for the older URLs we were using, and that when I updated the URLs this changed. Or possibly the older URLs represented a MaxMind policy that had different limits. In any case, there are strict download limits for the databases on the new URLs, and we are hitting it every day, causing downloader to fail.

This change will probably affect the download schedule for CAIDA Routeviews data too. However, it appears that CAIDA on [regenerates the database once a day](https://publicdata.caida.org/datasets/routing/routeviews-prefix2as/2024/03/), so downloading it more than that is wasteful.

Additionally, removes the MaxMind URL test. All the test did was to perform a HEAD request for the actual URL. However,
MaxMind logs the request and increments the daily limit counter for downloading databases (which has a max of 30 per day). If something is wrong in the code causing a build to fail and unit tests get run numerous times, testing alone
can exhaust the daily quota, even though nothing has actually been downloaded. And this affects all projects. So some debugging or adding a feature in sandbox could exhaust the daily quota, causing the production downloader to start
failing. This is counterproduction, and its not clear that we really benefit from running a HEAD request of every MaxMind URL on every test run.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/downloader/55)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Thanks. Is it possible to set up a non-production account instead of totally removing the test?

> *[Reviewable](https://reviewable.io/reviews/m-lab/downloader/55#-:-NtHpT4a8IEGtEv3GAb6:bxwczxs)* status: 0 of 2 files reviewed, all discussions resolved

**Review by nkinkade — COMMENTED** [review]
It could be possible to create another MaxMind account with a separate license key for testing. I'm not a huge fan of that idea for a couple main reasons:

* Having extra accounts laying around seems like one more thing to manage and maintain and keep track of credentials for.
* It doesn't necessarily resolve the issue of numerous build failures in a project causing builds to start failing because the quota was reached, though it would prevent the build failure from affecting production.
* Making HEAD requests against the live URLs just doesn't seem that useful. If the URLs are incorrect for some reason then we will get `DownloaderFailedToUpdate` alerts and can correct the problem. Verifying that the URLs work seems, to me, like something that needs to be done precisely once, not over and over again on every build.

@cristinaleonr, what do you think?

> *[Reviewable](https://reviewable.io/reviews/m-lab/downloader/55#-:-NtIIgbBDgXFWN4SORTI:b-1gif6)* status: 0 of 2 files reviewed, all discussions resolved

**Review by cristinaleonr — APPROVED** [review]
I think the main thing the test is checking is that we can reach the URL with our credentials. I suppose this check would not be as useful anyway if we used sandbox-specific credentials.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/downloader/55#-:-NtM7grLAmF4ETBOL4cP:brzqsdp)* status: 0 of 2 files reviewed, all discussions resolved

**Review by nkinkade — COMMENTED** [review]
Agreed. Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/downloader/55#-:-NtMRC3g01NRaJor4hgt:b-itl4qh)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
