### PR TITLE
Added the code for routeviews downloads.

### PR DESCRIPTION
**Pull request by jlm123hi**
This should be reviewed/merged only after the maxmind pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/downloader/4)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[download/maxmind.go, line 35 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr1VFDz3RWif1sxc8Cu:-Kr1VFDz3RWif1sxc8Cv:bxm2ldz) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/maxmind.go#L35)):*
> ```Go
> 		if err := RunFunctionWithRetry(Download, dc, waitAfterFirstDownloadFailure,
> 			maximumWaitBetweenDownloadAttempts); err != nil {
> ```

remove extra blank line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[download/routeviews_test.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr1YMrck4nn8M68hbi-:-Kr1YMrck4nn8M68hbi0:bymusxn) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/routeviews_test.go#L65)):*
> ```Go
> # the date in the filename, since file generation intentionally lags behind
> # a bit.
> # --------------------------------------------------------------------------
> ```

It happened before that routeviews update the old data w/ a newer version. So it is necessary to scan the directory and check whether the file is updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[download/routeviews.go, line 40 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr1t5SkxvpZNN5Wvx3C:-Kr1t5SkxvpZNN5Wvx3D:bqx6ynr) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/routeviews.go#L40)):*
> ```Go
> 		if err := RunFunctionWithRetry(Download, dc, waitAfterFirstDownloadFailure,
> 			maximumWaitBetweenDownloadAttempts); err != nil {
> ```

remove blank line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[download/common_test.go, line 94 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr21Iv-5jqxQj0uzyjG:-Kr21Iv-5jqxQj0uzyjH:bvdelgc) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/common_test.go#L94)):*
> ```Go
> }
> 
> func Test_download(t *testing.T) {
> ```

Change func name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[download/routeviews.go, line 21 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr21z1Ub3uDfctUkyf8:-Kr21z1Ub3uDfctUkyf9:b5pxav4) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/routeviews.go#L21)):*
> ```Go
> type UrlAndSeqNum struct {
> 	URL    string // The URL pointing to the file we need to download
> 	Seqnum int    // The seqnum of the file, as given in the routeview generation log file
> ```

put http://data.caida.org/datasets/routing/routeviews-prefix2as/pfx2as-creation.log in documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4)*

**Comment by jlm123hi** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[download/common_test.go, line 94 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr21Iv-5jqxQj0uzyjG:-Kr26Fyj7lc4CNrsg69R:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/common_test.go#L94)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Change func name
</blockquote></details>

Done.

---

*[download/maxmind.go, line 35 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr1VFDz3RWif1sxc8Cu:-Kr26TT-9DJ1PQmuh-DQ:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/maxmind.go#L35)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

remove extra blank line
</blockquote></details>

Done.

---

*[download/routeviews.go, line 21 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr21z1Ub3uDfctUkyf8:-Kr26tvMcwg4Hkm4m-KC:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/routeviews.go#L21)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

put http://data.caida.org/datasets/routing/routeviews-prefix2as/pfx2as-creation.log in documentation
</blockquote></details>

Done.

---

*[download/routeviews.go, line 40 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr1t5SkxvpZNN5Wvx3C:-Kr26SV636zaLeKr043M:b-896fix) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/routeviews.go#L40)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

remove blank line
</blockquote></details>

Done.

---

*[download/routeviews_test.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/downloader/4#-Kr1YMrck4nn8M68hbi-:-Kr287gfJCeJC4vXjRHq:b-f56wd1) ([raw file](https://github.com/m-lab/downloader/blob/60b2f21e8501d2e61d184506c6430ce6b9da6ccd/download/routeviews_test.go#L65)):*
> It happened before that routeviews update the old data w/ a newer version. So it is necessary to scan the directory and check whether the file is updated.
Disregard, as per in-person conversation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/downloader/4#-:-Kr2FKuqoO-jDonBKhda:bnfp4nl)*

**Pull request merged**
